# import env
Import('env')
env.Append(CPPPATH = ['/usr/include/glib-2.0/','/usr/lib/glib-2.0/include/','/usr/include/libpurple/','/usr/include'])
if( env['PLATFORM'] != 'win'):
    env.ParseConfig('pkg-config --cflags --libs glib-2.0 sqlite3')
objs = env.SharedObject([Glob('*.cpp')])
Return('objs')
