/* All functions must be camel case. */
[binding_model=by_value, include="link.h"] class Link {
    Link();
    [getter,setter] std::string name_;
    [getter,setter] std::string host_;
    [getter,setter] std::string status_;
};

