/* All functions must be camel case. */
[binding_model=by_value, include="postuiops.h"] class PostUiOps {
    PostUiOps();

    callback void NewPostCB(Post p, int rank);
    [setter] NewPostCB? newpostcb_;

    callback void PostMetricCB(std::string uuid, int metric);
    [setter] PostMetricCB? postmetriccb_;
};

