/* All functions must be camel case. */
[binding_model=by_value, include="rpl.h"] class rePoster {
    rePoster();
    void init();
    void startRepost();
    void stopRepost();

    Post newPost();
    void sendPost(Post p);

    /* Call back so when new posts come in we call */
    callback void NewPostCB(Post p);
    void setNewPostCB(NewPostCB? newPostCB);

    Account newAccount();
/*    Account[] getAccounts();*/
    void addAccount(Account newaccount);
    
    Link[] getLinks();
    void addLink(Link newlink);
};

