/* All functions must be camel case. */
[binding_model=by_value, include="rpl.h"] class rePoster {
    rePoster();
    void init();
    void startRepost();
    void stopRepost();

    void sendPost(Post p);

    /* Call back so when new posts come in we call */
    callback void NewPostCB(Post p, int rank);
    void setNewPostCB(NewPostCB? newPostCB);

    Account[] getAccounts();
    void addAccount(Account newaccount);
    void rmAccount(Account account);
    
    Link[] getLinks();
    void addLink(Link newlink);
    void rmLink(Link link);

    void getInitialPosts(NewPostCB? newPostCB);

};

